"""Scenario runner: boards, pictures, diagnostics, report.

    python3 -m rule_alpha.runner --out reports/rule_alpha
    python3 -m rule_alpha.runner --scenarios 01-normal-no-shelf --physics
"""

from __future__ import annotations

import argparse
import json
import pathlib
import time

from .config import DEFAULT_CONFIG, RuleAlphaConfig
from .episode import run_episode
from .scenarios import build_scenarios


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]


def _render_scenario(result, config, out_dir: pathlib.Path) -> list[str]:
    from .visualize import render_step

    report_root = out_dir.parent.parent  # reports/rule_alpha
    images: list[str] = []
    for mark in result.snapshots:
        for path in render_step(result, config, mark, out_dir):
            images.append(path.relative_to(report_root).as_posix())
    return images


def _row(result) -> dict:
    summary = result.summary
    rows = []
    for container in summary["containers"]:
        rows.append(
            {
                "container": container["container_index"],
                "placed_total": container["placed_total"],
                "shelf": container["container"]["has_shelf"],
                "priority": container["container"]["is_prioritized"],
                "floor_coverage": container["floor_coverage"],
                "largest_plateau_ratio": container["flatness"]["largest_plateau_ratio"],
                "largest_built_plateau_ratio": container["flatness"][
                    "largest_built_plateau_ratio"
                ],
                "plateau_count": container["flatness"]["plateau_count"],
                "local_roughness": container["flatness"]["local_roughness"],
                "height_spread": container["flatness"]["height_spread"],
                "structural_mask_fraction": container["flatness"]["masked_cell_fraction"],
                "interior_hole_count": container["holes"]["interior_hole_count"],
                "interior_hole_area": container["holes"]["interior_hole_area"],
                "largest_interior_hole_area": (
                    container["holes"]["largest_interior_hole"]["area"]
                    if container["holes"]["largest_interior_hole"] else 0.0
                ),
                "remaining_contiguous_free_area": container["holes"][
                    "largest_open_free_area"
                ],
                "largest_free_rect": container["holes"]["largest_open_free_rect"],
                "wall_height_ratio": container["wall_front"]["wall_height_ratio"],
                "wall_front_items": container["wall_front"]["wall_front_item_count"],
                "corridor_free_ratio": container["corridor"]["corridor_free_ratio"],
                "corridor_clear_lane_ratio": container["corridor"][
                    "corridor_clear_lane_ratio"
                ],
                "support_type_area": container["support_type_area"],
                "zones": container["zones"],
                **container["volume"],
            }
        )
    placed_volume = sum(r["placed_volume_m3"] for r in rows)
    usable_volume = sum(r["usable_container_volume_m3"] for r in rows)
    return {
        "scenario": summary["scenario"],
        "description": summary["description"],
        "placed_volume_m3": round(placed_volume, 5),
        "usable_container_volume_m3": round(usable_volume, 5),
        "volume_fill_ratio": round(placed_volume / max(usable_volume, 1e-9), 4),
        "official_evaluator_fill_score": None,
        "official_evaluator_fill_score_unavailable_reason":
            "physics run not requested (pass --physics)",
        "items_in_stream": summary["items_in_stream"],
        "items_placed": summary["items_placed"],
        "items_unplaced": summary["items_unplaced"],
        "stop_reason": summary["stop_reason"],
        "role_histogram": summary["role_histogram"],
        "archetype_histogram": summary["archetype_histogram"],
        "placed_class_histogram": summary["placed_class_histogram"],
        "runtime_seconds": summary["runtime_seconds"],
        "containers": rows,
    }


def _markdown(rows: list[dict], config: RuleAlphaConfig, images: dict) -> str:
    lines = [
        "# rule-alpha Layer 1 — scenario report",
        "",
        "Generated by `python3 -m rule_alpha.runner`.  Every number below is a "
        "*diagnostic*, not an objective: rule-alpha is a rule-based Layer 1 "
        "prototype whose purpose is to be looked at.",
        "",
        "See `docs/rule_alpha/README.md` for the rules, the classification and "
        "how to read the pictures.",
        "",
        "## Per-scenario headline",
        "",
        "| scenario | placed / stream | floor cov. | placed vol. m³ | "
        "usable vol. m³ | volume fill | structural m³ | foundation slab fill | "
        "official fill_score | "
        "largest plateau (of floor) | largest built plateau (of built) | "
        "plateaus | roughness | interior holes | largest hole | free rect | "
        "wall h/H | corridor lanes |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        for container in row["containers"]:
            label = row["scenario"]
            if len(row["containers"]) > 1:
                tag = "P" if container["priority"] else "N"
                label = f"{row['scenario']} (c{container['container']}·{tag})"
            lines.append(
                "| {name} | {placed}/{total} | {cov:.2f} | {vol:.3f} | "
                "{usable:.3f} | {vfill:.4f} | {struct:.3f} | {slab} | {official} | "
                "{plat:.2f} | "
                "{built:.2f} | {pc} | "
                "{rough:.3f} | {ih} | {lih:.3f} | {rect:.2f} | {wall:.2f} | "
                "{lane:.2f} |".format(
                    name=label,
                    placed=row["items_placed"],
                    total=row["items_in_stream"],
                    cov=container["floor_coverage"],
                    vol=container["placed_volume_m3"],
                    usable=container["usable_container_volume_m3"],
                    vfill=container["volume_fill_ratio"],
                    struct=container["structural_volume_m3"],
                    slab=(
                        f"{container['foundation_slab_fill_ratio']:.3f}"
                        if container["foundation_slab_fill_ratio"] is not None
                        else "n/a"
                    ),
                    official=(
                        f"{row['official_evaluator_fill_score']:.2f}"
                        if row["official_evaluator_fill_score"] is not None
                        else "null"
                    ),
                    plat=container["largest_plateau_ratio"],
                    built=container["largest_built_plateau_ratio"],
                    pc=container["plateau_count"],
                    rough=container["local_roughness"],
                    ih=container["interior_hole_count"],
                    lih=container["largest_interior_hole_area"],
                    rect=container["largest_free_rect"],
                    wall=container["wall_height_ratio"],
                    lane=container["corridor_clear_lane_ratio"],
                )
            )

    lines += [
        "",
        "## 3D fill by scenario",
        "",
        "`placed_count` / `floor_coverage` / `volume_fill_ratio` at a glance. "
        "Floor coverage is a 2D number — the share of usable floor with "
        "something standing on it — while `volume_fill_ratio` is 3D, so a "
        "board can cover the floor completely and still fill very little of "
        "the ULD. That gap is the size of the Layer 2 opportunity.",
        "",
        "| scenario | placed_count | floor_coverage | volume_fill_ratio |",
        "|---|---|---|---|",
    ]
    for row in rows:
        for container in row["containers"]:
            label = row["scenario"]
            if len(row["containers"]) > 1:
                tag = "P" if container["priority"] else "N"
                label = f"{row['scenario']} (c{container['container']}·{tag})"
            lines.append(
                "| {name} | {count} | {cov:.2f} | {vfill:.4f} |".format(
                    name=label,
                    count=container["placed_total"],
                    cov=container["floor_coverage"],
                    vfill=container["volume_fill_ratio"],
                )
            )

    lines += [
        "",
        "### What these mean",
        "",
        "- `placed_volume_m3` — sum of the oriented box volumes this container "
        "holds, floor and shelf alike. Structural cargo (wall-front, "
        "elongated, slope-infill) **is** included: the flatness metric masks "
        "it because it is meant to be tall, but occupied volume is occupied "
        "volume.",
        "- `usable_container_volume_m3` — the simulator's own "
        "`container.volume` (inner box, minus the chamfer wedge, minus the "
        "small shelf, minus the main shelf when present). This is the "
        "denominator `Evaluator.calculate_fill_rate` divides by, so it is "
        "taken from the observation when there is one and recomputed with the "
        "same formula otherwise.",
        "- `volume_fill_ratio` — the two above, divided. Layer 1 alone cannot "
        "fill a 1.5 m tall ULD, so single-digit percentages here are the "
        "expected result, not a failure.",
        "- `structural_volume_m3` — how much of the placed volume went into "
        "wall-front, elongated and slope structure. Counted in "
        "`volume_fill_ratio` like everything else; broken out because it is "
        "spent on structure rather than on foundation.",
        "- `foundation_slab_fill_ratio` — how densely and evenly the *normal* "
        "Layer 1 foundation was built: normal floor cargo volume ÷ (usable "
        "floor area × the height normal floor cargo reached). Shelf cargo, "
        "wall-front, elongated and slope structure are excluded from **both** "
        "sides — the same mask the flatness metric uses, and for the same "
        "reason: those pieces are deliberately tall, so letting one of them "
        "set the envelope height would make the foundation look full of air "
        "when it is not.",
        "- `official_evaluator_fill_score` — only from a `--physics` run, and "
        "only per scenario: the official evaluator scores a whole episode "
        "across all containers, so there is no per-container value. When it "
        "is `null` the row carries the reason.",
        "",
        "## Scenarios",
        "",
    ]
    for row in rows:
        lines += [
            f"### {row['scenario']}",
            "",
            row["description"],
            "",
            f"- stream: {row['items_in_stream']} items, "
            f"placed {row['items_placed']}, left for Layer 2+ "
            f"{row['items_unplaced']}",
            f"- stop reason: `{row['stop_reason']}`",
            f"- roles: `{row['role_histogram']}`",
            f"- winning archetypes: `{row['archetype_histogram']}`",
            f"- placed by class/surface: `{row['placed_class_histogram']}`",
            f"- 3D fill: placed `{row['placed_volume_m3']}` m³ of "
            f"`{row['usable_container_volume_m3']}` m³ usable = "
            f"`{row['volume_fill_ratio']}`",
            (
                f"- official evaluator fill_score: "
                f"`{row['official_evaluator_fill_score']}`"
                if row["official_evaluator_fill_score"] is not None
                else f"- official evaluator fill_score: `null` — "
                     f"{row['official_evaluator_fill_score_unavailable_reason']}"
            ),
            "",
        ]
        for container in row["containers"]:
            lines += [
                f"**container {container['container']}**"
                f"{' · priority' if container['priority'] else ''}"
                f"{' · shelf' if container['shelf'] else ''}",
                "",
                f"- floor coverage `{container['floor_coverage']}`, "
                f"largest plateau `{container['largest_plateau_ratio']}` of the "
                f"usable floor (largest *built* plateau "
                f"`{container['largest_built_plateau_ratio']}` of the built "
                f"surface) over `{container['plateau_count']}` plateaus, "
                f"height spread `{container['height_spread']}` m, "
                f"local roughness `{container['local_roughness']}` m",
                f"- structural cells masked out of flatness: "
                f"`{container['structural_mask_fraction']}`",
                f"- interior holes `{container['interior_hole_count']}` "
                f"totalling `{container['interior_hole_area']}` m², largest "
                f"`{container['largest_interior_hole_area']}` m²",
                f"- remaining contiguous free floor "
                f"`{container['remaining_contiguous_free_area']}` m² "
                f"(largest inscribed rectangle `{container['largest_free_rect']}` m²)",
                f"- slope wall front: `{container['wall_front_items']}` items, "
                f"wall_height / container_height = "
                f"`{container['wall_height_ratio']}`",
                f"- transport corridor free `{container['corridor_free_ratio']}`, "
                f"clear entry lanes `{container['corridor_clear_lane_ratio']}`",
                f"- 3D fill: placed `{container['placed_volume_m3']}` m³ "
                f"(floor `{container['placed_volume_floor_m3']}`, shelf "
                f"`{container['placed_volume_shelf_m3']}`, of which structural "
                f"`{container['structural_volume_m3']}`) of "
                f"`{container['usable_container_volume_m3']}` m³ usable = "
                f"`{container['volume_fill_ratio']}`",
                f"- foundation slab: normal floor cargo "
                f"`{container['foundation_volume_m3']}` m³ in a "
                f"{container['foundation_slab_height_m']} m slab "
                f"(`{container['foundation_slab_volume_m3']}` m³) = "
                f"`{container['foundation_slab_fill_ratio']}` — structural and "
                f"shelf cargo excluded from both sides",
                f"- typed support area: `{container['support_type_area']}`",
                "- zone occupancy: "
                + ", ".join(
                    f"`{zone}` {info['occupancy']:.2f}"
                    for zone, info in container["zones"].items()
                ),
                "",
            ]
        shots = images.get(row["scenario"], [])
        if shots:
            lines += [
                f"![{row['scenario']} final]({shots[-1]})",
                "",
                "Intermediate steps: "
                + ", ".join(
                    f"[{pathlib.PurePosixPath(shot).stem}]({shot})" for shot in shots
                ),
                "",
            ]

    lines += [
        "## Config used",
        "",
        "```json",
        json.dumps(config.to_dict(), indent=2, ensure_ascii=False),
        "```",
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=pathlib.Path,
                        default=REPO_ROOT / "reports" / "rule_alpha")
    parser.add_argument("--scenarios", type=str, default="",
                        help="comma separated scenario names (default: all)")
    parser.add_argument("--snapshots", type=int, default=3,
                        help="intermediate snapshots per scenario")
    parser.add_argument("--no-images", action="store_true")
    parser.add_argument("--physics", action="store_true",
                        help="also replay each scenario in PyBullet")
    parser.add_argument("--stop-on-unplaceable", action="store_true",
                        help="terminate like the official env instead of skipping")
    args = parser.parse_args(argv)

    config = DEFAULT_CONFIG
    wanted = {name for name in args.scenarios.split(",") if name}
    scenarios = [s for s in build_scenarios() if not wanted or s.name in wanted]
    if not scenarios:
        print("no scenarios matched")
        return 1

    out = args.out
    (out / "images").mkdir(parents=True, exist_ok=True)
    (out / "steps").mkdir(parents=True, exist_ok=True)

    rows, images, physics_rows = [], {}, []
    for scenario in scenarios:
        started = time.perf_counter()
        result = run_episode(
            scenario, config, snapshot_steps=args.snapshots,
            on_unplaceable="stop" if args.stop_on_unplaceable else "skip",
        )
        (out / "steps" / f"{scenario.name}.jsonl").write_text(
            result.to_jsonl(), encoding="utf-8"
        )
        rows.append(_row(result))
        if not args.no_images:
            scenario_dir = out / "images" / scenario.name
            scenario_dir.mkdir(parents=True, exist_ok=True)
            images[scenario.name] = _render_scenario(result, config, scenario_dir)
        print(
            f"[{scenario.name}] placed {result.summary['items_placed']}"
            f"/{result.summary['items_in_stream']} "
            f"in {time.perf_counter() - started:.1f}s",
            flush=True,
        )

        if args.physics:
            physics_row = _run_physics(scenario, config, out)
            physics_rows.append(physics_row)
            evaluation = physics_row.get("evaluation") or {}
            score = evaluation.get("fill_score")
            if score is None:
                rows[-1]["official_evaluator_fill_score_unavailable_reason"] = (
                    physics_row.get("error", "the physics run produced no evaluation")
                )
            else:
                rows[-1]["official_evaluator_fill_score"] = round(float(score), 4)
                rows[-1].pop(
                    "official_evaluator_fill_score_unavailable_reason", None
                )

    if physics_rows:
        (out / "physics.md").write_text(
            _physics_markdown(physics_rows), encoding="utf-8"
        )
    (out / "summary.json").write_text(
        json.dumps({"config": config.to_dict(), "scenarios": rows,
                    "physics": physics_rows},
                   indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    (out / "report.md").write_text(_markdown(rows, config, images), encoding="utf-8")
    print(f"wrote {out / 'report.md'}")
    return 0


def _physics_markdown(rows: list[dict]) -> str:
    lines = [
        "# rule-alpha in the official PyBullet environment",
        "",
        "Each scenario replayed through `GroundHandlingEnv`: real "
        "`check_inclusion`, real transport sweep, real 300-step settle.",
        "",
        "`accepted / attempted` counts placements the validator took. The run "
        "ends when rule-alpha declines, because Layer 1 has no home for the "
        "single visible item and this prototype has no Layer 2 — the official "
        "environment has no way to skip an item.",
        "",
        "| scenario | accepted / attempted | fill_score | items placed | seconds |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        if "error" in row:
            lines.append(f"| {row['scenario']} | — | error: {row['error']} | — | — |")
            continue
        evaluation = row.get("evaluation") or {}
        lines.append(
            "| {name} | {acc}/{att} | {fill:.2f} | {frac:.3f} | {secs} |".format(
                name=row["scenario"], acc=row["accepted"], att=row["attempted"],
                fill=float(evaluation.get("fill_score", 0.0)),
                frac=float(evaluation.get("num_placed_items", 0.0)),
                secs=row["runtime_seconds"],
            )
        )
    lines += [
        "",
        "A `fill_score` of 0.00 next to accepted placements is not a packing "
        "failure. `Evaluator.calculate_fill_rate` re-tests the *settled* pose "
        "against `inclusion_margin = -0.005`, and a box resting on the floor "
        "sits micrometres *inside* the floor plane, so its volume is "
        "discarded.",
        "",
        "The table demonstrates this on its own: the only scenario with a "
        "non-zero score is the only one that got cargo onto a **shelf**. Its "
        "floor-resting items scored nothing either — the shelf items are "
        "raised well clear of the floor plane, so they survive the margin. "
        "See the finding in `docs/rule_alpha/README.md` section 1.",
        "",
    ]
    return "\n".join(lines)


def _run_physics(scenario, config, out: pathlib.Path) -> dict:
    from .physics import run_physics_episode
    from .visualize import render_container

    try:
        result = run_physics_episode(scenario, config)
    except Exception as error:  # noqa: BLE001 - report, do not abort the sweep
        print(f"[{scenario.name}] physics run failed: {error}", flush=True)
        return {"scenario": scenario.name, "error": str(error)}

    directory = out / "images" / scenario.name
    directory.mkdir(parents=True, exist_ok=True)
    for index, (model, placements) in enumerate(
        zip(result["models"], result["placements"])
    ):
        render_container(
            model, placements, config,
            f"{scenario.name} | container {model.index} | PyBullet settled poses",
            directory / f"c{model.index}_physics.png",
        )
    accepted = sum(
        1 for step in result["steps"]
        if step.get("event") == "step" and step.get("settle_ok")
    )
    attempted = sum(1 for step in result["steps"] if step.get("event") == "step")
    print(
        f"[{scenario.name}] physics: {accepted}/{attempted} placements accepted "
        f"in {result['runtime_seconds']}s",
        flush=True,
    )
    (out / "steps" / f"{scenario.name}.physics.json").write_text(
        json.dumps(
            {
                "scenario": scenario.name,
                "runtime_seconds": result["runtime_seconds"],
                "evaluation": result["evaluation"],
                "steps": result["steps"],
            },
            indent=2, ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    return {
        "scenario": scenario.name,
        "attempted": attempted,
        "accepted": accepted,
        "evaluation": result["evaluation"],
        "runtime_seconds": result["runtime_seconds"],
    }


if __name__ == "__main__":
    raise SystemExit(main())
