"""Regress every official score component on num_placed_items.

Reads the feedback JSON blocks recorded verbatim in
docs/OFFICIAL_SCORE_LOG.md -- the only ground truth we have about the
evaluation platform -- and asks a question the raw component table
cannot answer: for each submission, was a component better or worse
than its own placed count predicts?

This matters because `num_placed_items` is known to gate the other
components with large amplification, so comparing two submissions'
components directly conflates "this change helped that axis" with
"this change placed more items". The residual against the placed trend
is the closest thing to a controlled comparison the five submissions
allow.

Caveats stated up front, because the numbers are seductive: n = 5, the
fit spends 2 degrees of freedom, and every component correlates with
placed at r > 0.96, so the residuals are small differences of large
numbers. Nothing here establishes a mechanism, and any extrapolation
beyond the observed placed range (0.434 to 0.505) is arithmetic, not
prediction.
"""

from __future__ import annotations

import argparse
import json
import math
import pathlib
import statistics

COMPONENTS = (
    "fill_score",
    "cog_score",
    "stability_score",
    "placement_score",
    "soft_item_score",
)
OBSERVED_RANGE_NOTE = (
    "observed num_placed_items range across the five submissions"
)


def parse_log(path: pathlib.Path) -> list[dict]:
    """Pull every feedback JSON object out of the score log, in order."""
    lines = path.read_text(encoding="utf-8").splitlines()
    blocks: list[dict] = []
    for start, line in enumerate(lines):
        if not line.startswith('{"fill_score"'):
            continue
        buffer = ""
        for offset in range(start, min(start + 8, len(lines))):
            buffer += lines[offset]
            try:
                blocks.append(json.loads(buffer))
                break
            except json.JSONDecodeError:
                continue
    return blocks


def pearson(xs: list[float], ys: list[float]) -> float:
    mx, my = statistics.fmean(xs), statistics.fmean(ys)
    sxy = sum((a - mx) * (b - my) for a, b in zip(xs, ys))
    sxx = sum((a - mx) ** 2 for a in xs)
    syy = sum((b - my) ** 2 for b in ys)
    return sxy / math.sqrt(sxx * syy)


def linear_fit(xs: list[float], ys: list[float]) -> tuple[float, float]:
    mx, my = statistics.fmean(xs), statistics.fmean(ys)
    sxy = sum((a - mx) * (b - my) for a, b in zip(xs, ys))
    sxx = sum((a - mx) ** 2 for a in xs)
    slope = sxy / sxx
    return slope, my - slope * mx


def analyze(blocks: list[dict], labels: list[str]) -> dict:
    placed = [b["num_placed_items"] for b in blocks]
    out: dict = {
        "submissions": labels,
        "num_placed_items": placed,
        "placed_range": [min(placed), max(placed)],
        "components": {},
    }
    for key in COMPONENTS:
        values = [b[key] for b in blocks]
        slope, intercept = linear_fit(placed, values)
        residuals = [
            v - (slope * p + intercept) for p, v in zip(placed, values)
        ]
        order = sorted(range(len(placed)), key=lambda i: placed[i])
        monotone = all(
            values[order[i]] < values[order[i + 1]]
            for i in range(len(order) - 1)
        )
        r = pearson(placed, values)
        out["components"][key] = {
            "values": values,
            "pearson_r": r,
            "r_squared": r * r,
            "monotone_in_placed": monotone,
            "slope_per_unit_placed": slope,
            "intercept": intercept,
            "residuals": residuals,
        }
    return out


def render_markdown(result: dict) -> str:
    labels = result["submissions"]
    placed = result["num_placed_items"]
    lines = [
        "# Official components regressed on num_placed_items",
        "",
        "Source: the feedback JSON blocks recorded verbatim in "
        "`docs/OFFICIAL_SCORE_LOG.md`. Generated by "
        "`scripts/analyze_official_components.py`.",
        "",
        "Comparing two submissions' components directly conflates "
        "\"this change helped that axis\" with \"this change placed more "
        "items\". The residual against each component's own placed trend "
        "is the closest thing to a controlled comparison five "
        "submissions allow.",
        "",
        "## Correlation with placed",
        "",
        "| component | r | r^2 | monotone in placed | slope per unit placed |",
        "|---|---:|---:|---|---:|",
    ]
    for key, stats in result["components"].items():
        lines.append(
            f"| `{key}` | {stats['pearson_r']:.4f} | "
            f"{stats['r_squared']:.4f} | "
            f"{'yes' if stats['monotone_in_placed'] else 'no'} | "
            f"{stats['slope_per_unit_placed']:.1f} |"
        )
    lines += [
        "",
        "## Residuals (positive = better than that submission's placed "
        "count predicts)",
        "",
        "| component | " + " | ".join(labels) + " |",
        "|---" * (len(labels) + 1) + "|",
    ]
    for key, stats in result["components"].items():
        cells = " | ".join(f"{r:+.2f}" for r in stats["residuals"])
        lines.append(f"| `{key}` | {cells} |")
    lines.append(
        "| `num_placed_items` | "
        + " | ".join(f"{p:.4f}" for p in placed)
        + " |"
    )
    lines += [
        "",
        "## Caveats",
        "",
        f"- n = {len(labels)}, and the fit spends 2 degrees of freedom.",
        "- Every component correlates with placed above r = 0.96, so the "
        "residuals are small differences of large numbers.",
        "- Correlation is not mechanism. A component could genuinely "
        "measure what its name says AND track placed.",
        f"- The {OBSERVED_RANGE_NOTE} is "
        f"{result['placed_range'][0]:.3f} to "
        f"{result['placed_range'][1]:.3f}. Evaluating a fit outside it "
        "is arithmetic, not prediction.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--log",
        type=pathlib.Path,
        default=pathlib.Path("docs/OFFICIAL_SCORE_LOG.md"),
    )
    parser.add_argument("--output-json", type=pathlib.Path, required=True)
    parser.add_argument("--output-md", type=pathlib.Path)
    parser.add_argument(
        "--labels",
        default="sub1-baseline,sub2,sub3-trueenvelope,sub4-deathband,"
        "sub5-quietguard",
    )
    args = parser.parse_args()

    blocks = parse_log(args.log)
    labels = [s.strip() for s in args.labels.split(",")]
    if len(labels) != len(blocks):
        raise SystemExit(
            f"parsed {len(blocks)} feedback blocks but got "
            f"{len(labels)} labels"
        )
    result = analyze(blocks, labels)
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(
        json.dumps(result, indent=1, ensure_ascii=False), encoding="utf-8"
    )
    print(args.output_json)
    if args.output_md:
        args.output_md.write_text(
            render_markdown(result), encoding="utf-8"
        )
        print(args.output_md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
