"""A physics-free packing episode you can actually train in.

`fast_afterstate_env` gives a heightmap board and a one-item afterstate.
What was missing was the loop: a visible pool, a candidate set, a
reward, and a terminal. This closes it, so a policy can be trained by
reinforcement instead of distilled from logged verdicts.

Two decisions carry the transfer, and both copy the published work
(`alexfrom0815/Online-3D-BPP-PCT`) rather than inventing:

* **Corner-anchored candidates, not a grid sweep.** The grid sweep in
  `fast_afterstate_env.enumerate_afterstates` costs 183 legality probes
  per placement at a 0.30 stride and still misses tight fits between the
  gridlines. Every good placement in a heightmap abuts something, so the
  candidate set is generated by aligning each item edge to each existing
  footprint edge (plus the container's own). Measured: the same episodes
  run about an order of magnitude faster and pack better.
* **Dense per-item reward.** `100 * item_volume / container_volume`, so
  the return of an episode is exactly the `fill_score_proxy` the
  simulator reports and the arena compares. No terminal is special: an
  episode that jams simply stops earning.

**Fidelity is not claimed here.** This model accepts a placement under
the shipped release contract (`Geometry.release_rejection_reason`), the
same call the agent's own release candidates pass, but it does not
settle anything. `reports/hazard/afterstate-fidelity.json` measures the
disagreement with physics and it is not small on release-candidate rows.
A policy trained here is a hypothesis until the arena scores it in
PyBullet.
"""

from __future__ import annotations

import pathlib
import sys
from typing import Any

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.fast_afterstate_env import CELL, AfterstateBoard

CONTRACT = "fast_packing_env_v1"
# Rounding used to dedupe candidate poses; finer than the heightmap cell
# so two genuinely different drops are never merged.
POSE_QUANTUM = CELL / 4.0


class FastPackingEnv:
    """One container, a visible pool, and legal placements for each item."""

    def __init__(
        self, agent_module, container: dict[str, Any],
        items: list[dict[str, Any]], *, lookahead: int = 10,
        per_item_candidates: int = 8, max_candidates: int = 64,
        grid_stride: float = 0.30,
    ):
        self.agent = agent_module
        self.container = container
        self.items = list(items)
        self.lookahead = int(lookahead)
        self.per_item_candidates = int(per_item_candidates)
        self.max_candidates = int(max_candidates)
        self.grid_stride = float(grid_stride)
        self._grid_x: set[float] = set()
        self._grid_y: set[float] = set()
        self.container_volume = (
            float(container["length"]) * float(container["width"])
            * float(container["height"])
        )
        self.reset()

    def reset(self, *, order: list[int] | None = None) -> None:
        self.board = AfterstateBoard(self.agent, self.container)
        self.stream = (
            [self.items[index] for index in order] if order is not None
            else list(self.items)
        )
        self.next_index = 0
        self.pool: list[dict[str, Any]] = []
        self._refill()
        # Footprint edges seeded from anything preloaded, so the first
        # placement already has real corners to abut rather than only the
        # container walls.
        self.footprints: list[tuple[float, float, float, float]] = []
        for packed, _soft, _prio in self.agent.packed_aabbs_local(
            self.container
        ):
            cx, cy, _cz = packed.center
            sx, sy, _sz = packed.size
            self.footprints.append(
                (float(cx), float(cy), float(sx), float(sy))
            )
        self.placed_volume = 0.0
        self.steps = 0

    def _refill(self) -> None:
        while len(self.pool) < self.lookahead and self.next_index < len(
            self.stream
        ):
            self.pool.append(self.stream[self.next_index])
            self.next_index += 1

    def _breakpoints(self) -> tuple[list[float], list[float]]:
        """Where an item edge is worth aligning to.

        Corner anchoring alone does not work on these containers. They
        are chamfered (``cut_x``/``cut_y``), so on an empty board the
        only breakpoints are the four walls and every wall-flush pose is
        outside the real envelope -- measured: zero legal candidates on
        an empty `dual-empty` board, where a 0.30 grid finds 66. A grid
        is therefore the floor of the candidate set, and footprint edges
        are added on top so a tight fit against a placed item stays
        reachable.

        A grid breakpoint is already a centre; a footprint edge is a
        line to align an item edge to. `_grid_x`/`_grid_y` is how
        `_item_candidates` tells the two apart.
        """
        self._grid_x = {
            float(v) for v in np.arange(
                self.board.x0 + self.grid_stride / 2.0,
                -self.board.x0, self.grid_stride,
            )
        }
        self._grid_y = {
            float(v) for v in np.arange(
                self.board.y0 + self.grid_stride / 2.0,
                -self.board.y0, self.grid_stride,
            )
        }
        xs = set(self._grid_x)
        ys = set(self._grid_y)
        for cx, cy, dx, dy in self.footprints:
            xs.add(cx - dx / 2.0)
            xs.add(cx + dx / 2.0)
            ys.add(cy - dy / 2.0)
            ys.add(cy + dy / 2.0)
        return sorted(xs), sorted(ys)

    def _item_candidates(
        self, pool_index: int, item: dict[str, Any],
        xs: list[float], ys: list[float],
    ) -> list[dict[str, Any]]:
        found: dict[tuple, dict[str, Any]] = {}
        for orientation in self.agent.unique_orientations(item):
            dx, dy, dz = self.agent.get_rotated_dimensions(
                item["length"], item["width"], item["height"], orientation
            )
            for bx in xs:
                for cx in ((bx,) if bx in self._grid_x
                           else (bx + dx / 2.0, bx - dx / 2.0)):
                    for by in ys:
                        for cy in ((by,) if by in self._grid_y
                                   else (by + dy / 2.0, by - dy / 2.0)):
                            key = (
                                int(orientation),
                                round(cx / POSE_QUANTUM),
                                round(cy / POSE_QUANTUM),
                            )
                            if key in found:
                                continue
                            # Anchoring an edge to a wall puts half the
                            # candidates outside the envelope, where the
                            # heightmap span is empty and drop_height has
                            # nothing to take a maximum over. The release
                            # contract would reject them anyway; rejecting
                            # them here is both cheaper and total.
                            if (
                                cx - dx / 2.0 < self.board.x0 - 1e-9
                                or cx + dx / 2.0 > -self.board.x0 + 1e-9
                                or cy - dy / 2.0 < self.board.y0 - 1e-9
                                or cy + dy / 2.0 > -self.board.y0 + 1e-9
                            ):
                                found[key] = None
                                continue
                            result = self.board.afterstate(
                                item, orientation, cx, cy
                            )
                            if result is None:
                                found[key] = None
                                continue
                            child, candidate = result
                            found[key] = {
                                "pool_index": pool_index,
                                "item": item,
                                "orientation": int(orientation),
                                "center": tuple(
                                    float(v) for v in candidate.center
                                ),
                                "size": (float(dx), float(dy), float(dz)),
                                "drop_height": float(
                                    candidate.center[2] - dz / 2.0
                                ),
                                "child": child,
                            }
        rows = [row for row in found.values() if row is not None]
        # Low first, then back-left: a deterministic order, and the one a
        # heightmap actually wants. The cap is what keeps the action set
        # the size PCT uses rather than the size a grid sweep produces.
        rows.sort(key=lambda row: (
            row["drop_height"], row["center"][0], row["center"][1]
        ))
        return rows[:self.per_item_candidates]

    def candidates(self) -> list[dict[str, Any]]:
        xs, ys = self._breakpoints()
        rows: list[dict[str, Any]] = []
        for pool_index, item in enumerate(self.pool):
            rows.extend(self._item_candidates(pool_index, item, xs, ys))
        rows.sort(key=lambda row: (
            row["drop_height"], row["center"][0], row["center"][1]
        ))
        return rows[:self.max_candidates]

    def step(self, candidate: dict[str, Any]) -> tuple[float, bool]:
        """Place the candidate; return its reward in fill points."""
        item = candidate["item"]
        dx, dy, dz = candidate["size"]
        cx, cy, _cz = candidate["center"]
        self.board = candidate["child"]
        self.footprints.append((cx, cy, dx, dy))
        self.pool.pop(candidate["pool_index"])
        self._refill()
        volume = (
            float(item["length"]) * float(item["width"])
            * float(item["height"])
        )
        self.placed_volume += volume
        self.steps += 1
        reward = 100.0 * volume / self.container_volume
        done = not self.pool
        return reward, done

    @property
    def fill(self) -> float:
        return 100.0 * self.placed_volume / self.container_volume

    def state_features(self) -> np.ndarray:
        board = self.board.features()
        return np.asarray([
            board.get("occupancy_mean", 0.0),
            board.get("occupancy_max", 0.0),
            board.get("occupancy_std", 0.0),
            board.get("roughness", 0.0),
            board.get("headroom_deficit", 0.0),
            board.get("floor_fraction_free", 0.0),
            board.get("placed", 0.0) / 40.0,
            len(self.pool) / max(1.0, float(self.lookahead)),
        ], dtype=np.float32)

    def candidate_features(
        self, rows: list[dict[str, Any]],
    ) -> np.ndarray:
        """Container-relative, so one policy serves every case geometry."""
        length = float(self.container["length"])
        width = float(self.container["width"])
        height = float(self.container["height"])
        out = np.zeros((len(rows), 10), dtype=np.float32)
        for index, row in enumerate(rows):
            cx, cy, cz = row["center"]
            dx, dy, dz = row["size"]
            out[index] = (
                cx / (length / 2.0), cy / (width / 2.0), cz / height,
                dx / length, dy / width, dz / height,
                row["drop_height"] / height,
                dx * dy * dz / self.container_volume,
                float(row["item"].get("is_prioritized", False)),
                float(row["item"].get("is_soft", False)),
            )
        return out
