"""Terrain survey of the shipped Layer 1, for the Layer 2 design discussion.

    python3 -m scripts.rule_alpha_terrain --out reports/rule_alpha

Runs every scenario against the analytic model, measures the surface Layer 1
leaves behind, and writes ``terrain.md`` / ``terrain.json`` plus one four-panel
picture per container.  It changes nothing in the planner; it only looks.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import time

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from rule_alpha import terrain as trn  # noqa: E402
from rule_alpha.config import DEFAULT_CONFIG  # noqa: E402
from rule_alpha.episode import run_episode  # noqa: E402
from rule_alpha.scenarios import build_scenarios  # noqa: E402


TARGET = """The zoning this survey is measured against (the target, not the
current behaviour):

| zone | intent |
|---|---|
| centre | normal-hard terraces; higher at the back, lower at the front, grown by Layer 2 |
| shelf | first home for soft / priority / SP — spend the headroom before going to the floor |
| left/right back | big or tall hard cargo; the outer anchor that keeps big items out of the centre |
| left/right front | low, fairly large hard; a landing pad for soft / priority overflow, ordinary support if none arrives |
| front centre | accessibility first — blocking it must cost more than blocking the front corners |
| chamfer | the progressive wedge staircase, as a local support-growth mechanism |
"""


def _fmt(value, digits: int = 3) -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def _cell_table(cells: dict) -> list[str]:
    rows = [
        "| cell | coverage | mean h | max h | hard top m² | soft top m² | items | first step |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for name in trn.CELLS:
        c = cells.get(name, {})
        if not c or c.get("usable_m2", 0.0) <= 0:
            rows.append(f"| `{name}` | — | — | — | — | — | — | — |")
            continue
        rows.append(
            f"| `{name}` | {_fmt(c['coverage'])} | {_fmt(c['mean_height_m'])} "
            f"| {_fmt(c['max_height_m'])} | {_fmt(c['hard_top_m2'], 4)} "
            f"| {_fmt(c['soft_top_m2'], 4)} | {c['items']} "
            f"| {_fmt(c['first_step'])} |"
        )
    return rows


def build(out_dir: pathlib.Path, config, scenarios, images: bool) -> dict:
    from rule_alpha.terrain_view import render_stack, render_terrain

    out_dir.mkdir(parents=True, exist_ok=True)
    image_dir = out_dir / "images"
    payload: dict = {"target_zoning": TARGET, "scenarios": []}

    for scenario in scenarios:
        started = time.perf_counter()
        result = run_episode(scenario, config)
        board = result.board
        entry = {
            "scenario": scenario.name,
            "description": scenario.description,
            "items_in_stream": result.summary["items_in_stream"],
            "items_placed": result.summary["items_placed"],
            "role_histogram": result.summary["role_histogram"],
            "containers": [],
            "images": [],
        }
        for idx in range(len(board.models)):
            model = board.model(idx)
            placements = board.placements[idx]
            entry["containers"].append(
                trn.container_terrain(model, placements, config)
            )
            if images:
                base = image_dir / scenario.name
                label = f"{scenario.name} — container {idx}"
                for written in render_stack(
                    model, placements, config,
                    f"{label} — how Layer 1 stacked it",
                    base / f"c{idx}_stack.png",
                ) + render_terrain(
                    model, placements, config,
                    f"{label} — Layer 1 terrain",
                    base / f"c{idx}_terrain.png",
                ):
                    entry["images"].append(
                        written.relative_to(out_dir).as_posix()
                    )
        entry["runtime_seconds"] = round(time.perf_counter() - started, 1)
        payload["scenarios"].append(entry)
        print(
            f"[{scenario.name}] placed {entry['items_placed']}"
            f"/{entry['items_in_stream']} in {entry['runtime_seconds']}s",
            flush=True,
        )

    (out_dir / "terrain.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=1) + "\n"
    )
    (out_dir / "terrain.md").write_text(render_markdown(payload))
    print(f"wrote {out_dir / 'terrain.md'}")
    return payload


def render_markdown(payload: dict) -> str:
    lines = [
        "# rule-alpha — what terrain does Layer 1 leave behind?",
        "",
        "Generated by `scripts/rule_alpha_terrain.py`.  Read-only survey of the",
        "shipped Layer 1: no rule was changed to produce it.",
        "",
        TARGET,
        "",
        "The reporting partition is 4 x 2 over the usable floor — `chamfer` /",
        "`left` / `centre` / `right` in x, `back` / `front` split at the middle",
        "of the depth — plus the shelf.  It is deliberately *not* the zone set",
        "the rules steer by, so the tables can show where the two disagree.",
        "",
        "## Headline",
        "",
        "| scenario | placed | NH y-centroid | NH back share | NH centre share "
        "| buildable | soft-capped m² | shelf fill | overflow "
        "| reach@floor | reach-back@0.4 |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for entry in payload["scenarios"]:
        c0 = entry["containers"][0]
        nh, b, sh = c0["normal_hard"], c0["buildable"], c0["shelf"]
        reach = c0["access"]["reach"]
        lines.append(
            f"| {entry['scenario']} | {entry['items_placed']}"
            f"/{entry['items_in_stream']} | {_fmt(nh['y_centroid'])} "
            f"| {_fmt(nh['back_share'])} | {_fmt(nh['centre_share'])} "
            f"| {_fmt(b['buildable_ratio'])} | {_fmt(b['soft_capped_area_m2'], 4)} "
            f"| {_fmt(sh['shelf_fill_ratio'])} | {sh['overflow_items']} "
            f"| {_fmt(reach['0.00']['reachable_ratio'])} "
            f"| {_fmt(reach['0.40']['reachable_back_ratio'])} |"
        )

    for entry in payload["scenarios"]:
        lines += ["", f"## {entry['scenario']}", "", entry["description"], ""]
        for image in entry["images"]:
            if image.endswith(".png"):
                lines.append(f"![{entry['scenario']}]({image})")
        lines.append("")
        for c in entry["containers"]:
            lines += [
                f"### container {c['container_index']}"
                f"  (shelf={c['has_shelf']}, priority={c['is_prioritized']},"
                f" placed={c['placed_total']})",
                "",
            ]
            lines += _cell_table(c["cells"])
            nh = c["normal_hard"]
            lines += [
                "",
                f"**normal-hard floor layer** — {nh['count']} items, "
                f"{_fmt(nh['footprint_m2'], 4)} m²; centroid "
                f"(x={_fmt(nh['x_centroid'])}, y={_fmt(nh['y_centroid'])}) in "
                f"normalised floor coordinates; back share "
                f"{_fmt(nh['back_share'])}, centre share "
                f"{_fmt(nh['centre_share'])}; mean top height by depth third "
                f"(front→back) {nh['height_by_y_third']}.",
                "",
                f"**surface** — buildable {_fmt(c['buildable']['buildable_ratio'])} "
                f"({_fmt(c['buildable']['buildable_area_m2'], 4)} m², "
                f"{c['buildable']['pad_count']} pads), soft-capped "
                f"{_fmt(c['buildable']['soft_capped_area_m2'], 4)} m². "
                f"Support area {c['support_area']}.  Height bands "
                f"{c['height_bands']}.",
                "",
                f"**shelf** — {c['shelf']}",
                "",
                f"**access** — {c['access']}",
                "",
                f"**tall structure** — {c['tall']['tall_perimeter_count']} "
                f"tall-perimeter items, back share "
                f"{_fmt(c['tall']['tall_perimeter_back_share'])}, median step "
                f"back {_fmt(c['tall']['tall_perimeter_median_step_back'])} vs "
                f"front {_fmt(c['tall']['tall_perimeter_median_step_front'])}.",
                "",
            ]
            if c["tall"]["items"]:
                lines += [
                    "| step | role | cell | height m | footprint m² | class |",
                    "|---|---|---|---|---|---|",
                ]
                for row in c["tall"]["items"]:
                    lines.append(
                        f"| {row['step']} | {row['role']} | `{row['cell']}` "
                        f"| {_fmt(row['height_m'])} "
                        f"| {_fmt(row['footprint_m2'], 4)} | {row['class']} |"
                    )
                lines.append("")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=pathlib.Path,
                        default=pathlib.Path("reports/rule_alpha"))
    parser.add_argument("--scenarios", type=str, default="")
    parser.add_argument("--no-images", action="store_true")
    args = parser.parse_args(argv)

    scenarios = build_scenarios()
    if args.scenarios:
        wanted = {s.strip() for s in args.scenarios.split(",") if s.strip()}
        scenarios = [s for s in scenarios if s.name in wanted]
    build(args.out, DEFAULT_CONFIG, scenarios, images=not args.no_images)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
